name: cuisinier
description: A smart way to process recipes and ingredients

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flare_flutter: ^2.0.6
  firebase_core: ^0.5.2+1
  google_sign_in: ^4.5.6
  firebase_auth: ^0.18.3+1
  google_fonts: ^1.1.1
  rflutter_alert: ^1.1.0
  cloud_firestore: ^0.14.3+1
  share: ^0.6.5+4
  image_picker: ^0.6.7+14
  http: ^0.12.2
  url_launcher: ^5.7.10
  font_awesome_flutter: ^8.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/flares/
    - assets/images/
